from .pathing import (
    COMMON_TDX_ROOTS,
    CONFIG_FILE,
    CONFIG_FILE_ENV_VAR,
    REGISTRY_KEY_PATHS,
    describe_tdx_user_dir_candidates,
    find_tdx_user_dir,
    is_mock_tdx_user_dir,
    iter_candidate_user_dir_specs,
    iter_candidate_user_dirs,
    load_config,
    resolve_config_file,
    save_config,
    set_tdx_user_dir,
)
